### PR TITLE
FIX create_default_pages = false still created default siteconfig

### PR DESCRIPTION
**Pull request by mikenz**
If we're not creating default pages, don't create default siteconfig either.

### CODE REVIEW

**Comment by dhensby** [comment]
Please can you explain the scenario where this is useful for you? 

I think this would be unexpected behaviour. Sites generally *need* a `SiteConfig` object and there's not normally a way to make one (as far as I recall). So I'm not sure how a developer who hadn't explicitly added logic to create their own `SiteConfig` would handle a scenario where no SiteConfig existed...

**Comment by tractorcow** [comment]
@mikenz would you accept `create_default_siteconfig` in place of this?

**Comment by tractorcow** [comment]
Also note that current_site_config() will STILL create the siteconfig; Removing it from requireDefaultRecords() only delays the construction, not prevent it.

**Comment by mikenz** [comment]
@tractorcow `create_default_siteconfig` would be good for me - happy to change the PR.
We want to be able to `/dev/build` to get a mostly empty database structure then push in test data that we use for our test automation. I'm guessing I put this change in our code when I first implemented that.

**Comment by tractorcow** [comment]
If you switch it to `create_default_siteconfig` and no other changes I'll accept that and merge it in.

**Comment by maxime-rainville** [comment]
@mikenz Are you still keen on getting this PR across the line?

**Comment by maxime-rainville** [comment]
I'll close this for now. If someone wants to pick it up again and put it over the line, just ping me and I'll reopen.

**Pull request closed without merging**
