### PR TITLE
API Support nested-themes API

### PR DESCRIPTION
**Pull request by tractorcow**
Merge with https://github.com/silverstripe/silverstripe-framework/pull/5826

### CODE REVIEW

**Comment by tractorcow** [comment]
We have discussed removing theme selection from siteconfig. Some developers have noted that the siteconfig theme selector has been mostly useless in their project. What are some thoughts from others?

**Comment by tractorcow** [comment]
I've raised a discussion point at https://groups.google.com/forum/#!topic/silverstripe-dev/feLc_tJksFo.

**Comment by wilr** [comment]
As long as individual Subsites still have a way to manage themes that seems reasonable.

**Comment by tractorcow** [comment]
Ok, I've now gone the other direction, and removed the theme selector, instead of complicating it. :)

**Comment by sminnee** [comment]
> As long as individual Subsites still have a way to manage themes that seems reasonable.

It might become a subsites feature instead.

**Comment by sminnee** [comment]
There are still tests for `SiteConfig::getAvailableThemes()` in there that are failing.

**Pull request merged**
