### PR TITLE
Added Helpful Robot badge

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by simonwelsh** [comment]
If you're going to use something like @mention-bot, please make sure it does not mention people who are no longer part of the project.

**Comment by dhensby** [comment]
@simonwelsh sorry, I've noticed this and will act on it soon.

**Comment by dhensby** [comment]
@simonwelsh I'll look into providing blocklists to our repos, because it does of course provide more value to us to get 3 people mentioned that are active contributers, but in the meantime see this issue https://github.com/facebook/mention-bot/issues/126#issue-155883284 we've opened and the solution where you can block mentionbot.

Is it acceptable for you to block the bot in the short term or do you rely on it for other projects?

**Comment by simonwelsh** [comment]
@dhensby have blocked the bot. Thanks! :)

**Comment by dhensby** [comment]
@simonwelsh we are now running our own version of @mention-bot and I've added you to an ignore list :)

**Pull request merged**
